# Generated by Django 4.1.1 on 2022-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Названия модели')),
                ('engine', models.IntegerField(blank=True, verbose_name='Двигатель модели')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('nm', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
