# Generated by Django 4.1.1 on 2022-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='engine',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Двигатель модели'),
        ),
        migrations.AlterField(
            model_name='model',
            name='hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='лошадинные силы'),
        ),
        migrations.AlterField(
            model_name='model',
            name='nm',
            field=models.IntegerField(blank=True, null=True, verbose_name='мощность'),
        ),
    ]
