# Generated by Django 4.1.1 on 2022-09-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('models', '0003_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
